# -*- coding: utf-8 -*-
"""Water and soil samples collected during a site visit.

A visit to a site can produce two campaigns — air and noise — and the samples
belong to neither. Putting them inside a campaign would mean the noise report
owning the water samples and the air report not, or storing them twice and
letting the two copies disagree. So they live in their own collection, tied to
the visit they came from.

Nothing reads them yet. There is no water or soil reporting engine, and this
deliberately does not pretend otherwise: what is recorded is what only the site
visit can produce and what cannot be reconstructed afterwards — when a sample
was taken, where, by whom, and a photograph of it.

What is deliberately absent: sample identifiers, container types,
preservatives, chain-of-custody signatures, laboratory destinations and test
results. A chain of custody is a legal record with rules about who signed for
what and when. Half-built, it produces a document that looks official and is
not — which is a worse outcome than having no such record at all. Those fields
belong with the reporting engine, designed against its actual requirements.
"""
from __future__ import annotations

import os
import uuid
from datetime import datetime
from typing import List, Optional

from fastapi import (APIRouter, Depends, File, Form, HTTPException, Response,
                     UploadFile, status)
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from audit import audit
from auth import current_username, require_admin
from db import db, to_mongo

router = APIRouter(tags=["site-samples"])

MEDIA_DIR = os.environ.get("MEDIA_DIR", "/data/attachments")
SAMPLE_KINDS = ("water", "soil")
# Photographs off a phone are a few megabytes; the ceiling is here to stop a
# mistake filling a 5 GB disk, not because a real photograph approaches it.
MAX_PHOTO_BYTES = 12 * 1024 * 1024


class SiteSample(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    # Generated by whatever recorded it — the phone for a field entry, the
    # server for one added by hand — and shared by every sample from the same
    # visit, which is what groups them.
    visit_id: str
    kind: str                                  # water | soil
    number: int                                # 1, 2, 3 … within its kind
    # Copied rather than referenced: a sample must still say where it came
    # from years later, whether or not the campaign still exists.
    project_name: Optional[str] = None
    client: Optional[str] = None
    site_name: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    accuracy_m: Optional[float] = None
    taken_at: Optional[datetime] = None        # naive local, as everywhere else
    recorded_by: Optional[str] = None          # the operator's own name
    note: Optional[str] = None
    photo_path: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    created_by: Optional[str] = None           # the signed-in account


class SampleUpdate(BaseModel):
    kind: Optional[str] = None
    number: Optional[int] = None
    project_name: Optional[str] = None
    client: Optional[str] = None
    site_name: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    taken_at: Optional[datetime] = None
    recorded_by: Optional[str] = None
    note: Optional[str] = None


@router.get("/site-samples", response_model=List[SiteSample])
async def list_samples(visit_id: Optional[str] = None,
                       kind: Optional[str] = None,
                       q: Optional[str] = None,
                       limit: int = 500) -> List[SiteSample]:
    """Newest first, because the useful question is nearly always what has
    just come in and not yet been taken to the laboratory."""
    query: dict = {}
    if visit_id:
        query["visit_id"] = visit_id
    if kind:
        query["kind"] = kind
    if q:
        rx = {"$regex": q, "$options": "i"}
        query["$or"] = [{"project_name": rx}, {"client": rx},
                        {"site_name": rx}, {"recorded_by": rx}]
    docs = await db.site_samples.find(query, {"_id": 0}) \
        .sort([("taken_at", -1), ("created_at", -1)]).to_list(limit)
    return [SiteSample(**d) for d in docs]


@router.post("/site-samples", response_model=SiteSample,
             status_code=status.HTTP_201_CREATED)
async def create_sample(
    visit_id: str = Form(...),
    kind: str = Form(...),
    number: Optional[int] = Form(None),
    project_name: Optional[str] = Form(None),
    client: Optional[str] = Form(None),
    site_name: Optional[str] = Form(None),
    latitude: Optional[float] = Form(None),
    longitude: Optional[float] = Form(None),
    accuracy_m: Optional[float] = Form(None),
    taken_at: Optional[datetime] = Form(None),
    recorded_by: Optional[str] = Form(None),
    note: Optional[str] = Form(None),
    photo: Optional[UploadFile] = File(None),
    x_user: str = Depends(current_username),
) -> SiteSample:
    if kind not in SAMPLE_KINDS:
        raise HTTPException(status.HTTP_400_BAD_REQUEST,
                            detail=f"kind must be one of {SAMPLE_KINDS}")

    # Numbered here when the caller does not say, so two phones recording the
    # same visit cannot both decide they are water sample 1.
    if number is None:
        number = 1 + await db.site_samples.count_documents(
            {"visit_id": visit_id, "kind": kind})

    sample = SiteSample(
        visit_id=visit_id, kind=kind, number=number,
        project_name=project_name, client=client, site_name=site_name,
        latitude=latitude, longitude=longitude, accuracy_m=accuracy_m,
        taken_at=taken_at, recorded_by=recorded_by, note=note,
        created_by=x_user,
    )

    if photo is not None and photo.filename:
        data = await photo.read()
        if len(data) > MAX_PHOTO_BYTES:
            raise HTTPException(status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                                detail="photograph too large")
        # Alongside every other attachment, on the persistent disk, so there
        # is one place where the files live and one thing to back up.
        dest_dir = os.path.join(MEDIA_DIR, "site_samples", visit_id)
        os.makedirs(dest_dir, exist_ok=True)
        ext = os.path.splitext(photo.filename)[1].lower() or ".jpg"
        path = os.path.join(dest_dir, f"{sample.id}{ext}")
        with open(path, "wb") as fh:
            fh.write(data)
        sample.photo_path = path

    await db.site_samples.insert_one(to_mongo(sample.model_dump()))
    await audit("site_sample.create", "site_sample", sample.id, x_user,
                {"kind": kind, "number": number, "visit_id": visit_id})
    return sample


@router.patch("/site-samples/{sample_id}", response_model=SiteSample)
async def update_sample(sample_id: str, payload: SampleUpdate,
                        x_user: str = Depends(current_username)) -> SiteSample:
    updates = {k: v for k, v in payload.model_dump().items() if v is not None}
    if not updates:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail="nothing to update")
    if "kind" in updates and updates["kind"] not in SAMPLE_KINDS:
        raise HTTPException(status.HTTP_400_BAD_REQUEST,
                            detail=f"kind must be one of {SAMPLE_KINDS}")
    res = await db.site_samples.find_one_and_update(
        {"id": sample_id}, {"$set": to_mongo(updates)},
        projection={"_id": 0}, return_document=True)
    if not res:
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail="sample not found")
    await audit("site_sample.update", "site_sample", sample_id, x_user, updates)
    return SiteSample(**res)


@router.get("/site-samples/{sample_id}/photo")
async def sample_photo(sample_id: str):
    doc = await db.site_samples.find_one({"id": sample_id}, {"_id": 0})
    if not doc or not doc.get("photo_path") or not os.path.exists(doc["photo_path"]):
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail="no photograph")
    return FileResponse(doc["photo_path"])


@router.delete("/site-samples/{sample_id}",
               status_code=status.HTTP_204_NO_CONTENT, response_class=Response)
async def delete_sample(sample_id: str,
                        admin: dict = Depends(require_admin)) -> Response:
    """Admin only, matching campaign deletion. A sample is evidence that
    somebody stood at a place at a time; whoever removes it should be the
    person answerable for the record."""
    doc = await db.site_samples.find_one({"id": sample_id}, {"_id": 0})
    if not doc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail="sample not found")
    if doc.get("photo_path") and os.path.exists(doc["photo_path"]):
        try:
            os.remove(doc["photo_path"])
        except OSError:
            pass                       # the record matters more than the file
    await db.site_samples.delete_one({"id": sample_id})
    await audit("site_sample.delete", "site_sample", sample_id,
                admin.get("username"), {"kind": doc.get("kind")})
    return Response(status_code=status.HTTP_204_NO_CONTENT)
